### ISSUE TITLE
RPERL

### ISSUE THREAD

**Issue by lbe** [yuki-kimoto/SPVM#2]
Is your goal similar to that of RPERL?

Thx 

Lbe

**Comment by yuki-kimoto** [comment]
@ibe

a little different.

RPerl is maybe compiled to C++(Machine code).
SPVM is virtual machin as similar as Java VM. 
SPVM have byte code you can see it spvm_bytecode.h

And SPVM plan is to call SPVM source code from Perl itself.
RPerl is single programing language, but SPVM is communicated with Perl.

My plan is the following.

    use SPVM 'SomeModule';

    my $result = SPVM::SomeModule::foo(1);

**Comment by rurban** [comment]
It's more similar to p2 and gperl. Both had a much better VM, but failed to implement all the perl5 features, esp. all the ops, the stdlib and all the crazy quirks of perl5.

But effectively SPVM is more like p5-in-p6 or PDL, optimizing only some modules.

rperl could do that also, because it's just an optional C++ wrapper for ops and data using libstdc++, but the current implementation is too strict. With the two planned rperl modes it would be similar to SPVM, rperl using cached Inline C++, SPVM using it's faster VM for certain parts.

**Comment by wbraswell** [comment]
There's lots of confusion in this discussion thread.  RPerl is not a "single programming language", rather it is a compiler for an ever-growing subset of Perl 5.  RPerl communicates directly with the Perl 5 core, which is written in C.

**Comment by yuki-kimoto** [comment]
@wbraswell 

Sorry, I misunderstood RPerl as a single programming language.
I feel now RPerl is a front end for Inline::C.

**Comment by wbraswell** [comment]
@yuki-kimoto 
RPerl is a Perl compiler, it can target any back-end, currently Inline::CPP is the primary back-end target because it can be made compatible with the Perl 5 core which is written in C.
